#!/bin/bash
# Auto-increment patch version and generate build-info.ts

set -e

# Read current version from package.json
CURRENT_VERSION=$(node -p "require('./package.json').version")

# Parse version (e.g., "0.1.5" -> major=0, minor=1, patch=5)
IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

# Increment patch version
PATCH=$((PATCH + 1))
NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"

# Update package.json with new version
node -e "
const fs = require('fs');
const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
pkg.version = '${NEW_VERSION}';
fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n');
"

echo "Version bumped: ${CURRENT_VERSION} -> ${NEW_VERSION}"

# Generate build timestamp
BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Generate build-info.ts
cat > src/build-info.ts << EOF
// Auto-generated by build script - DO NOT EDIT
export const BUILD_TIME = "${BUILD_TIME}";
export const VERSION = "${NEW_VERSION}";
EOF

# Run TypeScript compiler with rollback on failure
if ! tsc; then
  echo "❌ TypeScript compilation failed - rolling back version"

  # Restore package.json
  node -e "
  const fs = require('fs');
  const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
  pkg.version = '${CURRENT_VERSION}';
  fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n');
  "

  # Remove build-info.ts
  rm -f src/build-info.ts

  echo "Version rolled back: ${NEW_VERSION} -> ${CURRENT_VERSION}"
  exit 1
fi

echo "✅ Build successful (v${NEW_VERSION})"
