name: validation-pipeline
description: Run L1-L4 validation gates

stages:
  - name: lint
    nodes:
      - name: markdown-lint
        command: npm run lint:md
        timeout: 60
      - name: mermaid-validation
        command: cd tools && uv run ce validate --level 1
        timeout: 120
    parallel: false

  - name: test
    nodes:
      - name: unit-tests
        command: cd tools && uv run pytest tests/unit/ -v
        timeout: 300
      - name: integration-tests
        command: cd tools && uv run pytest tests/integration/ -v
        timeout: 600
    parallel: true
    depends_on: [lint]

  - name: validate
    nodes:
      - name: level-2-validation
        command: cd tools && uv run ce validate --level 2
        timeout: 300
      - name: level-3-validation
        command: cd tools && uv run ce validate --level 3
        timeout: 600
    parallel: false
    depends_on: [test]
