# Context Engineering Configuration

# PROFILE SECTION - Project-specific settings
# IMPORTANT: Fill in required fields (marked REQUIRED) before using system
# Fields with <missing> MUST be replaced with actual values
profile:
  # Project identification
  # REQUIRED - Used by Serena MCP for code navigation
  project_name: "<missing>"

  # Optional - Project description for documentation
  description: ""

  # Linear integration settings
  linear:
    # REQUIRED - Linear project name to assign issues to
    project: "<missing>"

    # REQUIRED - Default assignee email for PRP-generated issues
    assignee: "<missing>"

    # REQUIRED - Linear team identifier (from Linear API)
    team: "<missing>"

    # Optional - Default labels applied to new issues
    default_labels:
      - "feature"

  # Git defaults (optional - falls back to git config if empty)
  git:
    # Optional - Override git config user.name
    author_name: ""

    # Optional - Override git config user.email
    author_email: ""

  # Repository information (optional)
  repository:
    # Optional - Remote repository URL
    url: ""

    # Optional - Default branch name
    main_branch: "main"

# Framework settings (leave as-is unless customizing behavior)
cache:
  # TTL for drift analysis cache in minutes
  # Used by: ce analyze-context
  # Can be overridden with --cache-ttl flag
  analysis_ttl_minutes: 5

# Validation metadata (DO NOT EDIT)
# Used by framework to validate configuration completeness
_validation:
  # Required fields that must be filled (not <missing>)
  required_fields:
    - profile.project_name
    - profile.linear.project
    - profile.linear.assignee
    - profile.linear.team

  # Schema version for migration compatibility
  schema_version: "1.0.0"
