#!/usr/bin/env python3
"""
Repomix XML unpacker - extracts files from repomix-generated XML packages.

Since repomix CLI doesn't yet support --unpack, this utility extracts files
from XML packages generated by repomix.
"""

import argparse
import re
import sys
from pathlib import Path
from typing import List, Tuple


def parse_repomix_xml(xml_content: str) -> List[Tuple[str, str]]:
    """
    Parse repomix XML and extract (file_path, content) tuples.

    Args:
        xml_content: Raw XML content from repomix package

    Returns:
        List of (file_path, file_content) tuples
    """
    files = []

    # Pattern to match <file path="...">content</file>
    # Using non-greedy match and DOTALL to handle multiline content
    # Made newline before closing tag optional to catch files without trailing newlines
    pattern = r'<file path="([^"]+)">\n(.*?)\n?</file>'

    matches = re.finditer(pattern, xml_content, re.DOTALL)

    for match in matches:
        file_path = match.group(1)
        content = match.group(2)

        # Remove line number prefix (format: " 1: " or "   123→")
        # Each line in repomix XML has line numbers
        lines = content.split('\n')
        cleaned_lines = []
        for line in lines:
            # Match line number format: spaces + number + (→ or : + space)
            cleaned = re.sub(r'^\s*\d+[→:]\s*', '', line)
            cleaned_lines.append(cleaned)

        cleaned_content = '\n'.join(cleaned_lines)
        files.append((file_path, cleaned_content))

    return files


def extract_files(xml_path: Path, target_dir: Path, verbose: bool = False) -> int:
    """
    Extract all files from repomix XML to target directory.

    Args:
        xml_path: Path to repomix XML file
        target_dir: Directory to extract files to
        verbose: Print extraction progress

    Returns:
        Number of files extracted
    """
    if not xml_path.exists():
        print(f"❌ Error: XML file not found: {xml_path}", file=sys.stderr)
        return 0

    # Read XML content
    if verbose:
        print(f"📦 Reading package: {xml_path}")

    xml_content = xml_path.read_text()

    # Parse files
    files = parse_repomix_xml(xml_content)

    if not files:
        print(f"⚠️  Warning: No files found in package", file=sys.stderr)
        return 0

    if verbose:
        print(f"📋 Found {len(files)} files to extract")

    # Extract each file
    extracted = 0
    for file_path, content in files:
        # Construct full path
        full_path = target_dir / file_path

        # Create parent directories
        full_path.parent.mkdir(parents=True, exist_ok=True)

        # Write file
        full_path.write_text(content)

        if verbose:
            print(f"   ✓ {file_path}")

        extracted += 1

    return extracted


def main():
    """Main entry point for CLI."""
    parser = argparse.ArgumentParser(
        description="Extract files from repomix XML package",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Extract to current directory
  python repomix_unpack.py ce-infrastructure.xml

  # Extract to specific directory
  python repomix_unpack.py ce-infrastructure.xml --target /path/to/project

  # Verbose output
  python repomix_unpack.py ce-infrastructure.xml -v
        """
    )

    parser.add_argument(
        "xml_file",
        type=Path,
        help="Path to repomix XML file"
    )

    parser.add_argument(
        "--target",
        type=Path,
        default=Path.cwd(),
        help="Target directory for extraction (default: current directory)"
    )

    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Verbose output"
    )

    args = parser.parse_args()

    # Extract files
    count = extract_files(args.xml_file, args.target, args.verbose)

    if count > 0:
        print(f"\n✅ Extracted {count} files to {args.target}")
        return 0
    else:
        print(f"\n❌ Extraction failed", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
